baseurl = "https://berwout.nl/"
languageCode = "en-us"
title = "Berwouts' blog"

copyright = "&copy; Berwout 2021"

[params]
    GoogleAnalyticsID = "G-H7F3VBM96R"
    twitter = "@berwout_dvr"
    github = "nrg500"
    linkedin = "berwout-de-vries-robles-4712b355"
    author = "Berwout de Vries Robles"
    contact = "mailto:bdvr@Live.nl"
    subtitle = "A place to organize all my thoughts"