baseurl = "https://berwout.nl/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = "true"
title = "Berwouts' blog"
theme = "hamburg"

[params]
    # Short subtitle/tagline. This is displayed in the header.
    subtitle = "A place to organize all my thoughts"
    # Defines the tab color in Chrome for Android.
    themecolor = "#hexcolor"
    # To load additional CSS styles
    customCSS = ['hamburg.css']
    # Show this very user-friendly and absolutely not annoying GDPR notice at the bottom of the page
    ShowGDPRNotice = true
    # Since 0.57.0 there's the concept of "main sections". The files for the section "posts" are in "./content/posts/".
    mainSections = ["posts"]

[menu]

[languages]
    [languages.en]
        languageCode = "en"
        languageName = "English"
        subtitle = "A place to organize all my thoughts"
        # Copyright notice. This is displayer in the footer.
        copyright = "&copy; Berwout 2021"